#!/bin/bash

# This script run inside CONTAINER.

#Debbuging
#set -x                 # activate debugging from here
set +x # desactivate debugging from here

# Set values generated by singularity-init.sh in /tmp/value/
export HOME="$(cat /tmp/value/c_HOME_PATH)"
export HS_IDNUM="$(cat /tmp/value/IDNUM)"

# Set distro
export ROS_DISTRO=foxy

echo "+ [${HS_IDNUM}] Testing PX4 quadcopter - micrortps_agent +"

# Setting ROS2 + robofuzz enviroment
source "/opt/ros/$ROS_DISTRO/setup.bash"
source "/robofuzz/ros2_foxy/install/setup.bash"
source "/robofuzz/targets/px4_ros_com_ros2/install/setup.bash"
source "/robofuzz/targets/idltest_ws/install/setup.bash"
source "/robofuzz/targets/turtlebot3_ws/install/setup.bash"
source "/robofuzz/targets/moveit2_ws/install/setup.bash"

# Run agent
cd /robofuzz/src
micrortps_agent -t UDP
